Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 해다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
# 시리즈 클래스 만들기
# pandas 불러오기 (pd)
import pandas as pd



# k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1,'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# 리스트를 시리즈로 변환

list_data = ['2019-07-02', 3.14,'ABC',100,True]
#sr = pd.Series(list_data, index=list('abcde'))
sr= pd.Series(list_data)
print(sr,type(sr))

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(list(idx))
print(val)

RangeIndex(start=0, stop=5, step=1)
[0, 1, 2, 3, 4]
['2019-07-02' 3.14 'ABC' 100 True]


In [ ]:
#튜플을 시리즈로 변환
tup_data = ('lsh', '1999-07-30','남', False,[1,2,34])
sh = pd.Series(tup_data)
print(sh)

idx = sh.index
val = sh.values
print(idx)
print(val)

sr = pd.Series(tup_data, index = ['이름','생년월일', '성별','학생여부','ㅇㅇ'])
print(sr)

0           lsh
1    1999-07-30
2             남
3         False
4    [1, 2, 34]
dtype: object
RangeIndex(start=0, stop=5, step=1)
['lsh' '1999-07-30' '남' False list([1, 2, 34])]
이름             lsh
생년월일    1999-07-30
성별               남
학생여부         False
ㅇㅇ      [1, 2, 34]
dtype: object


In [ ]:
# 인덱싱
# import warnings
# warnings.filterwarnings('ignore')
print(sr[0])
print(sr['이름'])
print(sr[[1,2]]) # 시리즈에서 위치 기반 인덱싱을 사용해서 여러 요소를 선택 가능
#print(sr[1,2]) # 파이썬의 기본 인덱싱 방식으로 sr[1]과 같은 형태를 사용

lsh
lsh
생년월일    1999-07-30
성별               남
dtype: object


In [ ]:
# 배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [ ]:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
s3 =  pd.Series(data, index = state)

s3.name = 'population'
print(s3, type(s3))


Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64 <class 'pandas.core.series.Series'>


None 과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산 시 np.nan은 NaN 결과를 반환하는 반면 None은 TypeError를 발생시킨다

In [ ]:
s3.Califonia = np.nan
s3

Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
null_mask = s3.isnull()
null_mask

Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [ ]:
not_null_mask = s3.notnull()
not_null_mask

Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [ ]:
filled_series  = s3.fillna(0)
filled_series

Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
s3.isnull().sum()

1

In [ ]:
dropped_series = s3.dropna()
dropped_series

Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [ ]:
dropped_series.isnull().sum()

0

In [ ]:
print(s2, type(s2))

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# Series => List
list_from_series = s2.tolist()
list_from_series

[11, 13, 15, 17, 19]

In [ ]:
# Series => Dict
dict_from_series = s2.to_dict()
dict_from_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

In [ ]:
# Series => frame
df_from_series = s2.to_frame(name='Value')
df_from_series

Value
a     11
b     13
c     15
d     17
e     19

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])
s.x = np.nan
s.y = np.nan

s_ntoz = s.fillna(0)
s_nt = s_ntoz.isnull().sum()
print(f'{s_nt}개 있음')

0개 있음


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]
s = pd.Series(data_list)
s + 10

0    11
1    12
2    13
3    14
4    15
dtype: int64

Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
s = pd.Series([10,20,30,40,50],['a','b','c','d','e'])

s

a    10
b    20
c    30
d    40
e    50
dtype: int64

Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
d = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
s = pd.Series(d)
s[['b','d']]

b    2
d    4
dtype: int64

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부 확인후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

# 2. Null 값 2개 입력
s['y'] = np.nan
s['w'] = np.nan

# 3. Null 값을 0으로 대체
s.fillna(0, inplace=True)

# 4. Null 값 여부 확인
null_check = s.isnull()

# 5. 시리즈와 null 값 여부 출력
print(s)
print(null_check)



Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.



In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

# 리스트를 시리즈로 변환
series = pd.Series(data_list)

# 각 원소에 10을 곱한 시리즈 생성
new_series = series * 10

# 결과 출력
print(new_series)


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.


In [1]:
import pandas as pd

# 시리즈 생성
series = pd.Series([10, 20, 30, 40, 50], index=['a', 'c', 'b', 'd', 'e'])

# 인덱스를 기준으로 시리즈 정렬
sorted_series = series.sort_index()

# 결과 출력
print(sorted_series)


a    10
b    30
c    20
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

# 시리즈 생성
series = pd.Series(data, index=index)

# 인덱스 'b'와 'd'에 해당하는 원소 선택
selected_elements = series[['b', 'd']]

# 결과 출력
print(selected_elements)


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음


In [ ]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data)

df = pd.DataFrame(data,index=['d1','d2','d3'],
                  columns = ['pd','sales','inv'])

df


Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

iloc (Integer Location)
정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
loc (Label Location)
라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
양 끝점 포함: 슬라이싱 시 끝점을 포함.


In [2]:
import pandas as pd

# 데이터 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print(df, '\n')

# 첫 번째 행, 두 번째 열의 값 선택
print("첫 번째 행, 두 번째 열의 값:", df.iloc[0, 1], '\n')

# 첫 두 행과 첫 두 열을 선택
print(df.iloc[0:2, 0:2])



   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

첫 번째 행, 두 번째 열의 값: 5 

   A  B
0  1  5
1  2  6


In [ ]:
import pandas as pd

# 데이터 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data,index = ['a','b','c','d'])
print(df, '\n')

# 첫 번째 행, 두 번째 열의 값 선택
print("첫 번째 행, 두 번째 열의 값:", df.loc['a', 'B'])

# 첫 두 행과 첫 두 열을 선택
print(df.loc['a':'b','A':'B'])


In [ ]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data)

df = pd.DataFrame(data,index=['d1','d2','d3'],
                  columns = ['pd','sales','inv'])

df


In [ ]:
# pandas indexing : iloc 정수 인덱스 , loc 이름 인덱스
print(df.iloc[1],'\n')
print(df.loc['d2'])


In [ ]:
print(df.iloc[1,:],'\n')
print(df.loc['d2',:])


In [ ]:
print(df.iloc[1,2])
print(df.loc['d2','inv'])


In [ ]:
# d3 행에 0으로 바꾸기
df.loc['d3'] = 0
df


In [ ]:
# d4 행 생성
df.loc['d4']=0
df

# 확장할때는 iloc못씀 loc만 가능


In [3]:
# 열 생성
df.loc[:,"profit"] = 10
df
# lco[ , ] 안에:는 전부다 출력


A  B   C  profit
0  1  5   9      10
1  2  6  10      10
2  3  7  11      10
3  4  8  12      10

In [4]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)


0.0881452766528753 

1 

16.9544379846853 

4 

3 

[3, 4, 2] 

[2, 1, 4, 3, 5]


[numpy random 함수]


- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling



In [5]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성


0 

4 

[0 1 3 3 5 2 6 3 6 3] 

[10 10 17 10 18 12 13 19 17 10] 

[[11 11 11 18 13]
 [17 13 16 13 19]
 [15 12 14 14 19]]


In [6]:
# id , gender , age , region
import numpy as np
import pandas as pd
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size =1000)
g1 = pd.Series(gender)
age = np.random.randint(1,100,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)

df = pd.concat([i1,g1,a1,r1],axis=1)
df.rename(columns={0:"id",1:'gender',2:"age",3:"region"},inplace = True)
df.head()


id  gender  age  region
0   1       1    3       5
1   2       0   82      10
2   3       1   34       6
3   4       0   99       1
4   5       0   52      10

In [7]:
df.drop([0], axis=0,inplace = True)
df.head()


id  gender  age  region
1   2       0   82      10
2   3       1   34       6
3   4       0   99       1
4   5       0   52      10
5   6       0   87       1

loc와 at의 차이점

at은 라벨 기반 인덱싱을 사용. 단일값을 접근할때 loc접근자보다 빠르다.

여러 값을 동시에 접근하려면 loc 접근자를 사용


In [8]:
df.loc[5,'id']
df.at[5,'id']


6

In [ ]:
# 5번 인덱스의 행을 삭제
df1 = df.drop(index=5)

# 데이터프레임의 첫 7개 행 출력
print(df1.head(7))


In [ ]:
# df1 = df[:]
df1 = df.copy()
df1.head(3)
# df1.tail(3)


In [ ]:
np.random.seed(0)
a = np.random.randint(1,5,size=(10,5))
print(a,type(a))


In [ ]:
# 2차원 리스트를 데이터 프레임으로 변환
list1 = a.tolist()

df1= pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head())


In [ ]:
# 데이터프레임을 배열,리스트 ,딕셔너리로 변환
# 배열
ar = df1.values
print(ar,type(ar))

print()
# 리스트
li = ar.tolist()
print(li,type(li))

print()
# 딕셔너리
dict = df1.to_dict('list')
print(dict,type(dict))

