## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

In [ ]:
import pandas as pd

st1 = pd.Series({'국어':100, '영어':80,'수학':90})
st2 = pd.Series({'수학':80, '국어':90,'영어':80})

print(st1, '\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [ ]:
pd.DataFrame(st1+st2)

0
국어  190
수학  170
영어  160

In [ ]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
df = pd.concat([add,sub,mul,div], axis =1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00


In [ ]:
df = pd.concat([add,sub,mul,div],axis=1)
df.columns= ['덧셈','뺄셈','곱셈','나눗셈']
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [ ]:
print(add,type(add))

국어    190
수학    170
영어    160
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
result = pd.DataFrame([add,sub,mul,div])
result

국어       수학      영어
0   190.00   170.00   160.0
1    10.00    10.00     0.0
2  9000.00  7200.00  6400.0
3     1.11     1.12     1.0

In [ ]:
result = pd.DataFrame([add,sub,mul,div], index = ['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [ ]:
import numpy as np
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

st1 = st1.reindex(fill_value = 0)
st2 = st2.reindex(fill_value=0)

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)


result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [ ]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

st1 = st1.reindex(fill_value = 0)
st2 = st2.reindex(fill_value=0)

ad = st1.add(st2,fill_value=0)
su = st1.sub(st2,fill_value=0)
mu = st1.mul(st2,fill_value=0)
di = st1.div(st2,fill_value=0)


df = pd.DataFrame([ad,su,mu,di],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
df

국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [ ]:
np.arange(12.).reshape(3,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
print(df1)
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))
df2

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:

df2.loc[1,'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# 계산인자를 뒤집어 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [ ]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [ ]:
print(df1)
df1.rmul(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
# 배열의 연산 추가
arr = np.arange(12.).reshape(3,4)
print(arr, '\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [ ]:
#broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
z_to_bool = bool(0)
o_to_bool = bool(1)
print(z_to_bool)
print(o_to_bool)

In [ ]:
false_as_int = int(False)
true_as_int = int(True)
print(false_as_int)
print(true_as_int)

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [ ]:
import pandas as pd
import seaborn as sns

#titanic 데이터셋에서 age, sex, 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
#df = titanic.loc[:,['age','sex','class','fare','survived']]
df = titanic[['age','sex','class','fare','survived']]
print('승객 수 : ', len(df))
print(df.head())

승객 수 :  891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [ ]:
titanic.info()

In [ ]:
# class 열을 기준으로 분할(1개 열을 기준)
df1 = df[['age','fare','survived','class']]
grouped = df1.groupby(['class'])
print(grouped)
#list(grouped)

In [ ]:
# 그룹 객체를 iteration으로 출력 : head() 메소드로 첫 5행만을 출력
for key, group in grouped:
    print(' * key : ', key)
    print(' * number : ',len(group))
    print(group.head())

In [ ]:
# 연산 메소드 적용
average = grouped.mean()
print(average)

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363


In [ ]:
stat = grouped.max()
stat

age      fare  survived
class                           
First   80.0  512.3292         1
Second  70.0   73.5000         1
Third   74.0   69.5500         1

In [ ]:
# 개별 그룹 선택하기
group3 = grouped.get_group('Third')
print(group3.head())

    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [ ]:
group3.describe()

age        fare    survived
count  355.000000  491.000000  491.000000
mean    25.140620   13.675550    0.242363
std     12.495398   11.778142    0.428949
min      0.420000    0.000000    0.000000
25%     18.000000    7.750000    0.000000
50%     24.000000    8.050000    0.000000
75%     32.000000   15.500000    0.000000
max     74.000000   69.550000    1.000000

In [ ]:
# class 열, sex 열을 기준으로 분할(여러 열을 기준으로 분할)
df2 = df[['age','fare','survived','class','sex']]
grouped_two = df2.groupby(['class','sex'])

In [ ]:
# grouped_two 그룹 객체를 iteration으로 출력
for key, group in grouped_two:
    print(' * key', key)
    print(' * number', len(group))
    print(group.head())

 * key ('First', 'female')
 * number 94
     age      fare  survived  class     sex
1   38.0   71.2833         1  First  female
3   35.0   53.1000         1  First  female
11  58.0   26.5500         1  First  female
31   NaN  146.5208         1  First  female
52  49.0   76.7292         1  First  female
 * key ('First', 'male')
 * number 122
     age      fare  survived  class   sex
6   54.0   51.8625         0  First  male
23  28.0   35.5000         1  First  male
27  19.0  263.0000         0  First  male
30  40.0   27.7208         0  First  male
34  28.0   82.1708         0  First  male
 * key ('Second', 'female')
 * number 76
     age     fare  survived   class     sex
9   14.0  30.0708         1  Second  female
15  55.0  16.0000         1  Second  female
41  27.0  21.0000         0  Second  female
43   3.0  41.5792         1  Second  female
53  29.0  26.0000         1  Second  female
 * key ('Second', 'male')
 * number 108
     age  fare  survived   class   sex
17   NaN  13.0       

In [ ]:
# grouped_two 그룹 객체에 연산 메소드 적용
average_two = grouped_two.mean()
print(average_two)

                     age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


In [ ]:
print(type(average_two))

# grouped_two 그룹 객체에서 개별 그룹 선택하기
group3f = grouped_two.get_group(('Third','female'))
print(group3f.head())

<class 'pandas.core.frame.DataFrame'>
     age     fare  survived  class     sex
2   26.0   7.9250         1  Third  female
8   27.0  11.1333         1  Third  female
10   4.0  16.7000         1  Third  female
14  14.0   7.8542         0  Third  female
18  31.0  18.0000         0  Third  female


데이터 집계(agg),
- 집계 연산을 처리하는 사용자 정의 함수를 그룹 객체에 적용하려면 agg() 메서드 사용
- 모든열에 여러 함수를 매핑 : group객체.agg([함수1,함수2,함수3,…])
- 각 열마다 다른 함수를 매핑 : group객체.agg({‘열1’: 함수1, ‘열2’:함수2, …})

변환(transform)
- 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
- 데이터 변환 연산 : group객체.transform(매핑함수)

필터링(filter)
- 그룹 객체에 filter() 메서드를 적용할 때 조건식을 가진 함수를 전달하면 조건이 참인 그룹만을 남김
- 그룹 객체 필터링 : group 객체.filter(조건 함수식)

객체에 함수 매핑(apply)
 - 판다스 객체의 개별 원소를 특정 함수에 일대일로 매핑. 사용자가 원하는 대부분의 연산을 그룹 객체에 적용
 - group 객체.apply(매핑함수)

In [ ]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

In [ ]:
mean_all = grouped.mean()
print(mean_all)
print()
print(type(mean_all))

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

<class 'pandas.core.frame.DataFrame'>


In [ ]:
# class 지우기
mean_all.index.name = None
mean_all

age       fare  survived
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [ ]:
# 각 그룹에 대한 모든 열의 표준편차를 집계하여 데이터프레임으로 반환
std_all = grouped.std()
print(std_all)
print()
print(type(std_all))

              age       fare  survived
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

<class 'pandas.core.frame.DataFrame'>


In [ ]:
# 각 그룹에 대한 fare 열의 표준편차를 집계하여 시리즈로 반환
std_fare = grouped.fare.std()
print(std_fare)
print()
print(type(std_fare))

First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

<class 'pandas.core.series.Series'>


In [ ]:
# 그룹 객체에 agg() 메소드 적용 - 사용자 정의 함수를 인수로 전달
def min_max(x):    #최대값-최소값
    return x.max()-x.min()

#각 그룹의 최대값과 최소값의 차이를 계산하여 그룹별로 집계
agg_minmax = grouped.agg(min_max)
print(agg_minmax.head())

          age      fare  survived
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1


In [ ]:
# 모든열에 여러 함수를 매핑 : group객체.agg([함소1,함수2,함수3,***])
# 각 열마다 다른 함수를 매핑 : group객체.agg({'열1' : 함수1, '열2' : 함수2,***})

#agg_all = grouped.agg(['min','max','mean',min_max])
agg_all = grouped.agg(['min','max','mean'])
print(agg_all.head())

         age                  fare                      survived              
         min   max       mean  min       max       mean      min max      mean
First   0.92  80.0  38.233441  0.0  512.3292  84.154687        0   1  0.629630
Second  0.67  70.0  29.877630  0.0   73.5000  20.662183        0   1  0.472826
Third   0.42  74.0  25.140620  0.0   69.5500  13.675550        0   1  0.242363


In [ ]:
# 각 열마다 다른 함수를 적용하여 집게
agg_sep = grouped.agg({'fare':['min','max'], 'age':'mean'})
print(agg_sep.head())

       fare               age
        min       max min_max
First   0.0  512.3292   79.08
Second  0.0   73.5000   69.33
Third   0.0   69.5500   73.58


In [ ]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])
list(grouped)

[(('First',),
        age     sex  class     fare  survived
  1    38.0  female  First  71.2833         1
  3    35.0  female  First  53.1000         1
  6    54.0    male  First  51.8625         0
  11   58.0  female  First  26.5500         1
  23   28.0    male  First  35.5000         1
  ..    ...     ...    ...      ...       ...
  871  47.0  female  First  52.5542         1
  872  33.0    male  First   5.0000         0
  879  56.0  female  First  83.1583         1
  887  19.0  female  First  30.0000         1
  889  26.0    male  First  30.0000         1
  
  [216 rows x 5 columns]),
 (('Second',),
        age     sex   class     fare  survived
  9    14.0  female  Second  30.0708         1
  15   55.0  female  Second  16.0000         1
  17    NaN    male  Second  13.0000         1
  20   35.0    male  Second  26.0000         0
  21   34.0    male  Second  13.0000         1
  ..    ...     ...     ...      ...       ...
  866  27.0  female  Second  13.8583         1
  874  28.0  

In [ ]:
# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
grouped_filter = grouped.filter(lambda x: len(x)>=200)
print(grouped_filter.head())
print()
print(type(grouped_filter))

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

<class 'pandas.core.frame.DataFrame'>


#### 함수 매핑
커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map 함수는 Series의 각 요소에 함수를 적용.
- apply 함수는 Series 또는 DataFrame의 행이나 열에 함수를 적용.
- applymap 함수는 DataFrame의 각 요소에 함수를 적용.

In [ ]:
import pandas as pd
# 예제 Series 생성
s = pd.Series([1,2,3,4,5])

# 각 요소에 2를 더하는 함수
s_mapped = s.map(lambda x: x + 2)
print(s_mapped)

0    3
1    4
2    5
3    6
4    7
dtype: int64


In [ ]:
# DataFrame에 적용
# 예제 DataFrame 생성
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:

# 각 열에 대해 최대값을 구하는 함수
df_applied_col = df.apply(lambda x : x.max(), axis = 0 )
print(df_applied_col)

# 각 행에 대해 합계를 구하는 함수
df_applied_row = df.apply(lambda x: x.sum(), axis=1)
print(df_applied_row)

A    3
B    6
C    9
dtype: int64
0    12
1    15
2    18
dtype: int64


In [ ]:
# applymap 함수는 DataFrame에만 적용되며, 각 요소에 함수를 적용
# 예제 DataFrame 생성
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 각 요소에 2를 더하는 함수
df_applymapped = df.applymap(lambda x: x+2)
print(df_applymapped)

   A  B   C
0  3  6   9
1  4  7  10
2  5  8  11


In [ ]:
# 함수 적용과 매핑
import pandas as pd
import numpy as np
np.random.seed(10)
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037

In [ ]:
format = lambda x: '%.2f' %x

In [ ]:
# map함수는 series에만 적용
frame['e'].map(format)

Utah      -1.55
Ohio      -0.72
Texas      0.00
Oregon     1.20
Name: e, dtype: object

In [ ]:
# seires의 최대값과 최소값의 차이를 계산
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.506187
d    0.606730
e    2.748438
dtype: float64

In [ ]:
# 각 로우에 대해서 한 번씩 수행
frame.apply(f , axis='columns')

Utah      2.876987
Ohio      1.341422
Texas     0.261220
Oregon    1.377638
dtype: float64

In [ ]:
f1 = lambda x: round(x*10)
frame.apply(f1,axis=0)

b    d     e
Utah    13.0  7.0 -15.0
Ohio    -0.0  6.0  -7.0
Texas    3.0  1.0   0.0
Oregon  -2.0  4.0  12.0

In [ ]:
f1 = lambda x : round(x*20)
frame.apply(f1,axis =1)

b     d     e
Utah    27.0  14.0 -31.0
Ohio    -0.0  12.0 -14.0
Texas    5.0   2.0   0.0
Oregon  -3.0   9.0  24.0

In [ ]:
f1 = lambda x: sum(x)
frame.apply(f1, axis=1)

Utah      0.501465
Ohio     -0.107133
Texas     0.378352
Oregon    1.461463
dtype: float64

In [ ]:
frame

b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037

In [ ]:
# 여러값을 가진 Series 반환
print(frame, '\n')
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min','max'])
frame.apply(f)

               b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037 



b         d         e
min -0.174600  0.108549 -1.545400
max  1.331587  0.715279  1.203037

In [ ]:
# 실수값을 문자열 포맷으로 변환
format = lambda x: '%.2f' %x
frame.applymap(format)

b     d      e
Utah     1.33  0.72  -1.55
Ohio    -0.01  0.62  -0.72
Texas    0.27  0.11   0.00
Oregon  -0.17  0.43   1.20

In [ ]:
np.random.seed(0)
data = np.random.randint(1,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  45  48  65  68  68
1  10  84  22  37  88
2  71  89  89  13  59
3  66  40  88  47  89
4  82  38  26  78  73

In [ ]:
df['f'] = df.apply(lambda x: x.a+x.b+x.c+x.d+x.e ,axis=1)
df

a   b   c   d   e    f
0  45  48  65  68  68  294
1  10  84  22  37  88  241
2  71  89  89  13  59  321
3  66  40  88  47  89  330
4  82  38  26  78  73  297

In [ ]:
#표준화 : 데이터의 평균을 0, 표준편차를 1로 변환하는 과정. 이 과정을 통해 데이터의 스케일을 조정하고 비교 가능한 상태로 만듬
def z_score(x):
    return(x-x.mean()) / x.std()

In [ ]:
# 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
df_zscore = df.a.transform(z_score)
df_zscore

0   -0.344827
1   -1.576351
2    0.570020
3    0.394088
4    0.957070
Name: a, dtype: float64

In [ ]:
df_zscore =df.apply(lambda x:z_score(x))
df_zscore

a         b         c         d         e         f
0 -0.344827 -0.477299  0.215257  0.754401 -0.570413 -0.074984
1 -1.576351  0.978867 -1.107037 -0.451085  0.971244 -1.603498
2  0.570020  1.181112  0.953282 -1.384365 -1.264159  0.703693
3  0.394088 -0.800891  0.922531 -0.062219  1.048327  0.963252
4  0.957070 -0.881789 -0.984033  1.143268 -0.184999  0.011536

apply vs map
- apply는 DataFrame의 행이나 열 단위로 함수를 적용할 수 있지만, map은 Series의 각 요소에만 함수를 적용
- Series의 각 요소를 변환하는 간단한 작업에는 map이 적합하고, 더 복잡한 변환이 필요한 경우나 DataFrame 전체를 다룰 때는 apply가 유용

- df.apply는 DataFrame의 각 행(row) 또는 열(column)에 함수를 적용합니다. 기본적으로 axis=0으로 설정되어 있어 열 단위로 함수를 적용
- 각 행 또는 열 자체가 Series로 전달되며, 이 Series 전체에 대해 함수를 적용하려고 한다.
- applymap은 DataFrame의 모든 요소에 대해 함수를 적용하므로, 전체 DataFrame에 대한 변환이 필요할 때 유용

####Pivot
pivot 함수의 구성 형식
- index: 새로운 DataFrame에서 인덱스로 사용할 기존 열 또는 열들의 이름.
- columns: 새로운 DataFrame에서 열로 사용할 기존 열 또는 열들의 이름.
- values: 피벗할 때 사용할 값이 있는 열의 이름.

기능
- 긴 형식의 데이터를 넓은 형식으로 변환하여 특정 차원에서 데이터를 재구성.
- 피벗된 데이터를 통해 시간 경과에 따른 변화나 여러 카테고리의 비교를 쉽게 할 수 있다.
- 넓은 형식의 데이터는 시각화 도구에서 더 쉽게 다룰 수 있다.

In [ ]:
#날짜(date)를 인덱스로, 도시(city)를 열로, 온도(temperature)를 값을 사용하여 피벗 테이블을 생성
import pandas as pd

data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78]
}
df = pd.DataFrame(data)
print(df,'\n')
#피벗 테이블 생성
pivot_df=df.pivot(index = 'date', columns='city', values='temperature')
print(pivot_df)

         date         city  temperature
0  2021-01-01     New York           32
1  2021-01-01  Los Angeles           75
2  2021-01-02     New York           30
3  2021-01-02  Los Angeles           78 

city        Los Angeles  New York
date                             
2021-01-01           75        32
2021-01-02           78        30


In [ ]:
# 중복된 값을 평균으로 처리하여 피벗 테이블을 생성
data = {
    'date': ['2021-01-01', '2021-01-01','2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78,50]
}

df = pd.DataFrame(data)

#피벗 테이블 생성 (중복 값의 평균 계산)
pivot_table_df = df.pivot_table(index = 'date',columns='city',values='temperature', aggfunc = 'mean')
print(pivot_table_df)

city        Los Angeles  New York
date                             
2021-01-01           75        31
2021-01-02           50        78


In [ ]:
data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78],
    'humidity': [80, 20, 85, 15]
}
df = pd.DataFrame(data)
print(df,'\n')
pivot_multi_df = df.pivot(index='date',columns='city')
print(pivot_multi_df)

         date         city  temperature  humidity
0  2021-01-01     New York           32        80
1  2021-01-01  Los Angeles           75        20
2  2021-01-02     New York           30        85
3  2021-01-02  Los Angeles           78        15 

           temperature             humidity         
city       Los Angeles New York Los Angeles New York
date                                                
2021-01-01          75       32          20       80
2021-01-02          78       30          15       85


In [ ]:
import pandas as pd

data = {
    'Year': [2020, 2020, 2021, 2021, 2022, 2022, 2022, 2023, 2023],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'C', 'A', 'C'],
    'Sales': [100, 150, 200, 250, 300, 350, 400, 500, 450]
}


df_pivot = df.pivot(values = 'Sales',index = 'Year', columns = 'Product', aggfunc = 'sum', fill_value=0)
df_pivot

TypeError: DataFrame.pivot() got an unexpected keyword argument 'aggfunc'

In [ ]:

df_pivot = pd.pivot(values = 'Sales',index = 'Year', columns = 'Product', aggfunc = 'sum', fill_value=0)
df_pivot

Q.주어진 직원 근무 시간 데이터에서 ,각 직원별로 각 월의 총 근무 시간을 계산하세요


In [ ]:
data = {
    'Employee': ['John', 'John', 'John', 'Anna', 'Anna', 'Anna', 'Peter', 'Peter', 'Peter'],
    'Month': ['Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar'],
    'Hours': [160, 170, 175, 150, 165, 180, 155, 160, 170]
}

df = pd.DataFrame(data)
print(df)

df_pivot = df.pivot(values = 'Hours', index = 'Employee', columns= 'Month',aggfunc =sum,fill_value=0)
df_pivot

  Employee Month  Hours
0     John   Jan    160
1     John   Feb    170
2     John   Mar    175
3     Anna   Jan    150
4     Anna   Feb    165
5     Anna   Mar    180
6    Peter   Jan    155
7    Peter   Feb    160
8    Peter   Mar    170


Month     Feb  Jan  Mar
Employee               
Anna      165  150  180
John      170  160  175
Peter     160  155  170

In [ ]:
data = {
    'Employee': ['John', 'John', 'John', 'Anna', 'Anna', 'Anna', 'Peter', 'Peter', 'Peter'],
    'Month': ['Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar'],
    'Hours': [160, 170, 175, 150, 165, 180, 155, 160, 170]
}

df = pd.DataFrame(data)
print(df)

df_pivot = df.pivot(values = 'Hours', index = 'Employee', columns= 'Month')
df_pivot