Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [ ]:
D = np.diag([1, 2, 3])
D1 = np.linalg.inv(D)
print(D1)
D @ D1

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
A = np.random.rand(3, 3)
Au = np.triu(A)
print(Au)

print('\n')

Al = np.tril(Au)
print(Al)

[[0.57979967 0.55821489 0.84239667]
 [0.         0.12089193 0.31144289]
 [0.         0.         0.78702106]]


[[0.57979967 0.         0.        ]
 [0.         0.12089193 0.        ]
 [0.         0.         0.78702106]]


In [1]:
import numpy as np
A = np.random.rand(3, 3)
Au = np.triu(A)

Au_T = Au.T
print(Au_T)


[[0.61860216 0.         0.        ]
 [0.19459592 0.82890159 0.        ]
 [0.25086602 0.11691906 0.36599204]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [2]:
A = np.array([[4,7],[2,6]])
a1 = np.linalg.inv(A)
print(a1)
np.dot(A, a1)

#확인하느법
np.allclose(np.dot(A, a1), np.eye(2))

[[ 0.6 -0.7]
 [-0.2  0.4]]


True

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [3]:
import numpy as np
X = np.array([[1, 2, 3]])
w = np.array([
    [0.5],
    [1.5],
    [-2]
])

y = np.dot(w, X)
print(y)

[[-2.5]]


In [8]:
import numpy as np

# 입력 데이터 포인트
X = np.array([1, 2, 3])

# 모델 파라미터
w = np.array([0.5,1.5,-2])

# 예측값 계산
y_pred = np.dot(w, X)

# 결과 출력
print(y_pred)

-2.5


#### 행렬곱을 할 때 연산의 순서
연산의 순서는 매우 중요하며, 결과가 달라질 수 있습니다. 주어진 입력과 가중치에 대해 원하는 연산이 무엇인지에 따라 올바른 순서를 선택

np.dot(X,W)와 np.dot(W,X)
- np.dot(X,W)는 X가 (1x3) 벡터이고, W가 (3x3) 행렬이므로, 결과는 (1x3) 벡터입니다.
- np.dot(W,X)는 W가 (3x3) 행렬이고, X가 (3,) 벡터이므로, 결과는 (3,) 벡터입니다.
- 둘 중 어느 것을 선택해야 하는지는 연산의 의미에 따라 결정
  - 입력 벡터 X를 가중치 행렬 W에 곱하여 새로운 출력 벡터를 계산하는 경우
  np.dot(X,W)를 사용.
  - 가중치 행렬 W를 입력 벡터 X에 곱하여 각 출력 뉴런에 대한 값을 계산하는 경우 np.dot(W,X)를 사용.

Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

X = np.array([0.5, 1.0, -1.5])

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [6]:
# 가중치 = 파라미터 # W는 가중치 행렬, X는 입력 벡터이고 일반적인 표기 방식은 WX
X = np.array([0.5, 1.0, -1.5])
w = np.random.randn(3, 3)
print(X,'\n')
print('\n',w,'\n')
z = np.dot(w, X) # 가중치가 먼저
print(z)

[ 0.5  1.  -1.5] 


 [[ 0.16608978  0.21423465  0.32532993]
 [-0.87892551  0.83048387 -0.24589429]
 [-1.79194539 -0.39506291 -1.85182968]] 

[-0.19071536  0.75986256  1.48670891]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산<br>
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [9]:
X = np.array([1, -2, 3])
W = np.array([
    [1],
    [0.5],
    [2]
])
b = np.array([
    [1],
    [1],
    [1]
])
print(np.dot(X, W),'\n')

Z = np.dot(X, W) + b
print(Z)

[6.] 

[[7.]
 [7.]
 [7.]]


In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(Z)

array([[0.99908895],
       [0.99908895],
       [0.99908895]])

In [17]:
import numpy as np
#화성화 함수 정의
def relu(x):
    return np.maximum(0,x)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 입력 벡터 정의
X = np.array([1, -2, 3])
# 가중치 행렬과 편향 벡터 정의
W = np.random.randn(3,3)
b = np.array([0.1,-0.2,0.3])

#신경망의 선형 변환 계산
Z = np.dot(W,X) +b
relu_output = relu(Z)
sigmoid_output = sigmoid(Z)

print(relu_output, sigmoid_output)

[4.22348048 0.11688064 6.64560522] [0.98556388 0.52918694 0.99870197]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.


[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
A = np.array([
    [3, 4],
    [2, 1]
])
b = np.array([
    [10],
    [5]
])
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[[2.]
 [1.]]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p'에서 원래 좌표 p를 복원.

In [2]:
import numpy as np
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])
print(p,'\n')
print(T,'\n')
p_new = np.dot(p, T)
print(p_new,'\n')


p_old = np.dot(np.linalg.inv(T), p_new)
print(p_old)

[1 2] 

[[2 0]
 [0 3]] 

[2 6] 

[1. 2.]


In [ ]:
p @ T @ np.linalg.inv(T)

array([1., 2.])

In [18]:
import numpy as np
# 원래 점의 좌표 p와 반환 행렬 T를 정의
p = np.array([1,2])
T = np.array([[1,2], [0,3]])

# 새로운 좌표 p'계산
p_prime = np.dot(T,p)

# 변환 행렬 T의 역행렬 계산
T_inv = np.linalg.inv(T)

#원래 좌표 p 복원
p_restored = np.dot(T_inv, p_prime)