Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [4]:
D = np.diag([1, 2, 3])
D1 = np.linalg.inv(D)
print(D1)
D @ D1

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [7]:
A = np.random.rand(3, 3)
Au = np.triu(A)
print(Au)

print('\n')

Al = np.tril(Au)
print(Al)

[[0.57979967 0.55821489 0.84239667]
 [0.         0.12089193 0.31144289]
 [0.         0.         0.78702106]]


[[0.57979967 0.         0.        ]
 [0.         0.12089193 0.        ]
 [0.         0.         0.78702106]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [9]:
A = np.array([[4,7],[2,6]])
a1 = np.linalg.inv(A)
print(a1)
np.dot(A, a1)

[[ 0.6 -0.7]
 [-0.2  0.4]]


array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [25]:
import numpy as np
X = np.array([[1, 2, 3]])
w = np.array([
    [1],
    [1],
    [1]
])

y = np.dot(X, w)
print(y)

[[6]]


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

X = np.array([0.5, 1.0, -1.5])

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [15]:
X = np.array([0.5, 1.0, -1.5])
w = np.array([
    [1],
    [2],
    [-1]
])
print(X,'\n')
print('\n',w,'\n')
z = np.dot(X, w)
print(z)

[ 0.5  1.  -1.5] 


 [[ 1]
 [ 2]
 [-1]] 

[4.]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [24]:
X = np.array([1, -2, 3])
W = np.array([
    [1],
    [0.5],
    [2]
])
b = np.array([
    [1],
    [1],
    [1]
])
print(np.dot(X, W),'\n')

Z = np.dot(X, W) - b
print(Z)

[6.] 

[[5.]
 [5.]
 [5.]]


In [22]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(Z)

array([[0.99330715],
       [0.99330715],
       [0.99330715]])

Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [27]:
A = np.array([
    [3, 4],
    [2, 1]
])
b = np.array([
    [10],
    [5]
])
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[[2.]
 [1.]]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [31]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])
print(p,'\n')
print(T,'\n')
p_new = np.dot(T, p)
print(p_new,'\n')


p_old = np.dot(np.linalg.inv(T), p_new)
print(p_old)

[1 2] 

[[2 0]
 [0 3]] 

[2 6] 

[1. 2.]


In [30]:
p @ T @ np.linalg.inv(T)

array([1., 2.])