NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

1. NumPy 기본 개념
  - NumPy는 과학 계산을 위한 Python 라이브러리.
  - 다차원 배열 객체인 ndarray를 중심으로 작동.
  - 벡터화 연산, 브로드캐스팅 기능을 제공.

2. NumPy 배열 생성 및 조작
  - np.array(): 리스트나 튜플로부터 배열 생성.
  - np.arange(), np.linspace(): 연속된 값으로 배열 생성.
  - 배열의 형태 변경: reshape(), flatten() 등.

3. 배열 인덱싱 및 슬라이싱
  - 배열 요소에 접근하고 수정하는 방법.
  - 슬라이싱을 사용해 배열의 부분집합 추출.

4. NumPy의 수학적 연산
  - 기본 수학 연산: 덧셈, 뺄셈, 곱셈, 나눗셈.
  - 통계 연산: mean(), median(), std(), sum() 등.
  - 선형 대수 연산: 내적, 외적, 행렬 곱셈.

5. 브로드캐스팅:
  - 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능.
  - 브로드캐스팅 규칙 이해 및 적용.

6. 부울 인덱싱 및 팬시 인덱싱
  - 조건에 맞는 데이터 선택.
  - 특정 인덱스 집합에 대한 데이터 접근.

7. 파일 입출력
  - NumPy 배열을 파일로 저장하고 불러오기: np.save(), np.load().

8. 실용적 예제: 데이터 분석에 NumPy 활용
  - 실제 데이터셋을 가지고 기본적인 데이터 처리 및 분석 수행.

Numpy Documentation  

In [1]:
# 배열 생성 및 기본 작업
import numpy as np

#Creating a NumPy array
array = np.array([1,2,3,4])

# Basic operations
print('Original array:', array)
print('Array + 2 :', array+2)
print('Array squard :', array**2)


# Basic statistics
print('Mean of array:', np.mean(array))

Original array: [1 2 3 4]
Array + 2 : [3 4 5 6]
Array squard : [ 1  4  9 16]
Mean of array: 2.5


In [2]:
# 배열 생성 및 속성 탐색:
# Create a ID array from a list
array_1d = np.array([3,6,9,12])
print(" ID Array:", array_1d)

# Array attributes
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Type:", array_1d.dtype)

# Create a 2D array using a nested list
array_2d = np.array([[1,2,3,],[4,5,6]])
print("\n 2D Array: \n:", array_2d.shape)
print("Shape:", array_2d.size)
print("Shape:", array_2d.dtype)

 ID Array: [ 3  6  9 12]
Shape: (4,)
Size: 4
Type: int64

 2D Array: 
: (2, 3)
Shape: 6
Shape: int64


In [3]:
print(array_1d, '\n')
print(array_2d)

[ 3  6  9 12] 

[[1 2 3]
 [4 5 6]]


In [4]:
# 인덱싱 및 슬라이싱:
#indexing
print('\nElement at index:', array_1d[2])

# Slicing
print('Elements from index 1 to 3:', array_1d[1:4])

# 2D Array Indexing
print("\nElement in 2nd row, 3rd column:", array_2d[1,2])

#Slicing in 2d
print("First row:", array_2d[0,:])
print("first row:", array_2d[0])
print("first column:", array_2d[:,0])
print("first column:", array_2d[:,:])



Element at index: 9
Elements from index 1 to 3: [ 6  9 12]

Element in 2nd row, 3rd column: 6
First row: [1 2 3]
first row: [1 2 3]
first column: [1 4]
first column: [[1 2 3]
 [4 5 6]]


In [5]:
# Creating two arrays
a= np.array([1,2,3])
b= np.array([4,5,6])

#Addition
print("Addition:",a+b)

#Subtraction
print("Subtraction:", a-b)

# Element-wise multiplication
print("Multiplcation:", a*b)

# Division
print("Division:",a/b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplcation: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [6]:
array = np.array([1,2,3,4])

print('따블', array**2)

따블 [ 1  4  9 16]


#### 파이썬 리스트와 넘파이 배열의 주요 차이점

데이터 타입:
- 파이썬 리스트: 다양한 타입의 데이터를 저장할 수 있다. 즉, 하나의 리스트에 정수, 문자열, 객체 등 다양한 타입의 요소를 포함할 수 있다.
- 넘파이 배열: 모든 요소가 동일한 데이터 타입을 가져야 한다. 이는 메모리 사용과 계산 속도를 최적화하는 데 도움이 된다.

메모리 사용:
- 파이썬 리스트: 비연속적으로 메모리에 요소를 저장. 각 요소는 객체로서 별도의 메모리 공간을 차지하며, 리스트는 이러한 객체들의 참조를 저장.
- 넘파이 배열: 모든 요소가 연속된 메모리 블록에 저장. 이는 데이터 접근과 조작을 더 빠르고 효율적으로 만든다.

성능:
- 파이썬 리스트: 다양한 타입의 데이터를 유연하게 처리할 수 있지만, 이로 인해 넘파이 배열에 비해 연산 속도가 느릴 수 있다.
- 넘파이 배열: 수학적이고 과학적인 계산에 최적화되어 있으며, 특히 대량의 데이터를 다룰 때 높은 성능을 제공.

크기 조정:
- 파이썬 리스트: 동적으로 크기가 조정. 요소를 추가하거나 제거하면 리스트의 크기가 자동으로 변경.
- 넘파이 배열: 고정된 크기를 가진다. 배열의 크기를 변경하려면 새로운 배열을 생성하고 기존 데이터를 복사해야 한다.

다양한 기능과 연산:
- 파이썬 리스트: 기본적인 연산과 기능을 제공.
- 넘파이 배열: 다차원 배열을 지원하며, 선형대수, 통계, 푸리에 변환 등 고급 수학적 및 과학적 연산을 위한 광범위한 함수와 메서드를 제공.

용도:
- 파이썬 리스트: 일반적인 프로그래밍 작업 및 다양한 타입의 데이터를 유연하게 관리할 때 사용.
- 넘파이 배열: 과학 계산, 데이터 분석, 대규모 수치 연산 등에서 주로 사용.

결론적으로, 파이썬 리스트는 유연성과 범용성에 초점을 맞추고 있으며, 넘파이 배열은 고성능 수치 계산과 데이터 처리에 최적화되어 있다.

In [7]:
li = [1,'a']
print(f1,type(li))

NameError: name 'f1' is not defined

In [ ]:
ar = np.array([1,'a'])
print(ar,type(ar))

In [ ]:
z = np.arange(10)
print(z)
print(z.size)
print(z.itemsize)

In [ ]:
z = np.arange(5)
print(f'{z.size*z.itemsize} bytes')

In [ ]:
# Numpy 는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
import numpy as np
my_arr = np.arange(10000000)
my_list = list(range(1000000))

In [ ]:
#  "_"은 값을 무시하고 싶은 경우 사용(여기서는 인덱스 무시)
# %time는 뒤따르는 한 줄의 코드 실행 시간을 측정하는 매직 명령어
%time for _ in range(10): my_array2 = my_arr *2


In [ ]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

In [ ]:
# 배열 연산
data = np.random.randn(2,3)
print(data, '\n')
print(data * 10,'\n')
print(data +data)

In [ ]:
print(data.ndim)

(3, 2, 5) : 배열이 3개의 (2x5) 행렬로 구성
- 첫 번째 차원 (Depth): 최상위 레벨에 3개의 배열
- 두 번째 차원 (Rows): 각 최상위 배열은 2개의 하위 배열
- 세 번째 차원 (Columns): 각 하위 배열은 5개의 요소


In [ ]:
# 3차원
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                   [[1,2,3,4,5],[6,7,8,9,10]],
                   [[1,2,3,4,5],[6,7,8,9,10]]])
print(array3, array3.shape, '\n')
print(type(array3))

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [ ]:
# zeros가 입력으로 튜플을 받기 때문에 두 번 괄호 사용
print(np.zeros(10))
print(np.zeros((3,6)))
print(np.zeros((2,3,2)))

In [ ]:
a = np.arange(10).reshape(2,5)
a

In [ ]:
a = np.arange(10).reshape(2,5)
z = np.zeros_like(a)
o = np.ones_like(a)
f = np.full_like(a,5)
print(z,'\n')
print(o,'\n')
print(f)

In [ ]:
# arange 함수 : 파이썬의 range함수의 배열 버전
arr3 = np.arange(15)
arr3

In [ ]:
arr_1d = np.arange(6)
arr_2d = arr_1d.reshape(2,3)
arr_3d = arr_1d.reshape(2,3,1)
print(arr_1d, '\n')
print(arr_2d, '\n')
print(arr_3d)

Q. 1차원 배열을 생성한 후 -1을 이용해서 배열의

In [ ]:
ar = np.arange(12)
ar

In [ ]:

print('1차원 => 2차원: \n', ar.reshape(3,-1),'\n')
print('1차원 => 2차원: \n', ar.reshape(3,4),'\n')
print('1차원 => 3차원: \n', ar.reshape(2,3,-1),'\n')
print('1차원 => 3차원: \n', ar.reshape(2,3,2),'\n')

In [ ]:
ar = np.arange(30).reshape(2,-1)
ar

In [ ]:
ar21 = ar.reshape(-1,)
print(ar21,'\n')
ar23 = ar.reshape(-1,2,5)
print(ar23,)

In [ ]:
# 모양 변경 및 크기 조절
import numpy as np

# Reshaping
a = np.arange(6)
reshaped = a.reshape(2,3)
print("Reshaped Array:\n", reshaped)

# Resizing
resized = np.resize(a,(3,2))
print("Resized Array: \n", resized)

In [ ]:
a= np.arange(6)
reshaped = a.reshape(2,3)
reshaped

In [ ]:
# Splitting : 배열을 여러 하위 배열로 나눈다.
split1, split2 = np.split(reshaped,2)
print('Split Arrays:\n', split1,"\n",split2)

In [ ]:
a  = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
print(a,'\n')
print(b)

In [ ]:
a  = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

#Concatenating
concatenated = np.concatenate((a,b), axis=0)
print('Concatenated Array:\n', concatenated)

#Stacking
stacked = np.vstack((a,b,a,b,a,b,a,b))
print("Stacked Array:\n", stacked)

In [ ]:
array1 = np.arange(30)
array3d = array1.reshape(3,2,5)
print(array3d, '\n', type(array3d),'\n')
li = array3d.tolist()
print(li, '\n',type(li))

Q. 1차원 배열을 생성해서 2차원 배열로 변환한 후 다음 사항을 수행하세요
- 2차원 배열을 리스트로 타입 변경하세요.
- 리스트를 다시 배열로 변경하세요.

In [ ]:
#1차원 배열생성
ar = np.arange(20)
#2차원 배열로 변환
ar1 = ar.reshape(4,5)
#2차원 배열을 리스트로 변환
li = ar1.tolist()
li
#리스트를 다시 배열로 변경
ar2 = np.array(li)
ar2

Q. 두 배열 [[1, 2], [3, 4]]와 [[5, 6], [7, 8]]를 가로로 연결하기

In [ ]:
a1 = np.array([1,2,3,4])
b1 = np.array([5,6,7,8])
a2 = a1.reshape(2,2)
b2 = b1.reshape(2,2)
concatenated = np.concatenate((a2,b2), axis=1)
concatenated

Q.두 배열 [[1, 2, 3]]와 [[4, 5, 6]]을 세로로 연결하기

In [ ]:
a1 = np.array([[1,2,3]])
b1 = np.array([[4,5,6]])
concatenated = np.concatenate((a1,b1), axis = 0)
concatenated

In [ ]:
a1 = np.array([[1,2,3]])
b1 = np.array([[4,5,6]])
stacked = np.vstack((a1,b1))
stacked

Q. 배열 [0, 1, 2, 3, 4, 5, 6, 7, 8]를 세 부분으로 나누기

In [ ]:
a1 = np.array([0,1,2,3,4,5,6,7,8])
baby1, baby2, baby3 = np.split(a1,3)

print(baby1,'\n',baby2,'\n',baby3)

In [ ]:
# 기본 통계 연산
import numpy as np
#Creating an array
data = np.array([1,2,3,4,5])


#Mean
print('Mean:', np.mean(data))

print('Median:', np.median(data))

print('Standard Deviation:', np.std(data))

In [ ]:
# 수학적 함수:

# Creating an array
angles = np.array([0, np.pi/2, np.pi])
angles

In [ ]:
# Sin function
print("Sine:", np.sin(angles))
# Cosine function
print('Cosine:', np.cos(angles))

# Exponential function
print("Exponetial:", np.exp([1,2,3]))

In [ ]:
# 부동 소수점 연산에서 발생하는 미세한 오차로 0에 가까운 값으로 출력될 수 있음

pi_value = np.pi
result = np.sin(pi_value)
print(result)

In [ ]:
from PIL import Image
import matplotlib.pyplot as plt

# Replace 'image_name.jpg' with your image file's name
image = Image.open('/content/drive/MyDrive/kdt_240224/m3_분석라이브러리/numpy/KakaoTalk_20240605_121559345 (1).jpg')
plt.imshow(image)
plt.axis('off')  # Turn off axis numbers
plt.show()

NumPy에서 부호없는 양수 정수형(unsigned integer)

음수가 없고 0과 양의 정수만을 표현할 수 있는 데이터 유형.<br>
이는 일반적으로 데이터를 저장할 때 필요한 메모리 크기를 최적화하는 데 사용.<br>  
부호없는 정수형 데이터 타입은 numpy 모듈에서 제공하며, 각 타입은 표현할 수 있는 값의 범위에 따라 구분. <br><br>

numpy.uint8: 8비트 부호없는 정수<br>
값의 범위: 0 ~ 255<br>
예: numpy.uint8(255)<br><br>
numpy.uint16: 16비트 부호없는 정수<br>
값의 범위: 0 ~ 65535<br>
예: numpy.uint16(65535)<br><br>
numpy.uint32: 32비트 부호없는 정수<br>
값의 범위: 0 ~ 4294967295<br>
예: numpy.uint32(4294967295)<br><br>
numpy.uint64: 64비트 부호없는 정수<br>
값의 범위: 0 ~ 18446744073709551615<br>
예: numpy.uint64(18446744073709551615)<br><br>

이러한 부호없는 정수형은 이미지 처리, 바이너리 데이터 저장, 비트 연산 등에서 자주 사용. 예를 들어, 8비트 부호없는 정수는 이미지의 픽셀 값을 표현하는 데 유용하며, 16비트 부호없는 정수는 더 큰 범위의 데이터를 처리할 때 유용.

In [ ]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr3 = np.array([1,2,3])
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype=np.float64)
int_array = int_array.astype(calibers.dtype)
print(int_array, int_array.dtype)

Q. int_array의 dtype을 정수(int32)로 변경하세요

In [ ]:
int_array.astype(np.int32)

int32 와 int64의 차이 : 정수의 범위와 메모리 사용량
1. int32
- 32비트 정수를 저장
- 범위: -2,147,483,648에서 2,147,483,647까지의 정수를 표현
2. int64
- 64비트 정수를 저장
- 범위: -9,223,372,036,854,775,808에서 9,223,372,036,854,775,807까지의 정수를 표현

In [ ]:
# zeros 함수 : shape과 dtype을 입력받아 0으로 초기화된 배열을 만들어준다.
# empty 함수 : shape과 dtype을 입력받아 0으로 초기화되지 않은 배열을 만들어준다.
# 특정 크기와 데이터 타입을 가진 새로운 배열을 빠르게 생성, 배열의 요소는 임의의 값으로 채워진다(메모리에 이미 존재하는 값).
print(np.empty(shape=(10,), dtype=np.int8))
print(np.zeros(shape=(10,), dtype=np.int8))

In [ ]:
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

In [ ]:
# 문자열 타입으로 배열 만들기( S: 바이트 문자열)
import numpy as np

arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
numeric_string = np.array(['1.25','-9.5','42'], dtype=np.string_)# dtype=np.string_는 배열의 데이터 타입이
#바이트 문자열임을 명시. dtype='S'와 동일
print(numeric_string


      )
numeric_string.astype(float)

[Random 함수]  

- np.random.seed       # seed를 통한 난수 생성
- np.random.randint    # 균일분포의 정수 난수 1개 생성
- np.random.rand       # 0부터 1사이의 균일분포에서 난수 매트릭스 array 생성
- np.random.randn      # 가우시안 표준 정규 분포에서 난수 매트릭스 array 생성
- np.random.shuffle    # 기존의 데이터의 순서 바꾸기
- np.random.choice     # 기존의 데이터에서 sampling

In [ ]:
# 0부터 1사이의 균일분포에서 난수 매트릭스 array 생성
print(np.random.rand(5),'\n')
# 0~1사이의 균일 분포로 구성된 5행 5열의 배열읠 생성
print(np.random.rand(5,5))

In [ ]:
import numpy as np
print(np.random.choice([1,2,3,4,5],10),'\n')
print(np.random.choice([1,2,3,4,5]),'\n')
print(np.random.choice(10,5,replace=False),'\n')
np.random.choice(10,9)

In [ ]:
#np.uniform: 균일 분포를 따르는 난수 생성
print(np.random.uniform(1,2,3),'\n')
print(np.random.uniform(0,1,(2,3)),'\n')
np.random.uniform(1,2,10)

In [ ]:
import random
pop =[1,2,3,4,5]
sample= random.sample(pop,3)
print(sample)
print(pop)

In [ ]:
# 중복 혀옹햐지 않는 numpy 샘플링

In [ ]:
#np.random.random_sample은 중복 혀용
r_ar = np.random.random_sample(486546454)
unique_values = len(np.unique(r_ar))
total_values = len(r_ar)
print(f"Unique values : {unique_values}")
print(f"Total values : {total_values}")


Q. 정수와 실수로 구성된 list_e = [1,2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.

In [ ]:
import numpy as np
list_e = [1,2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1, array_e1.dtype)
array_e2 = array_e1.astype('int32')
print(array_e2, array_e2.dtype)

In [ ]:
#배열의 연산
import numpy as np
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr, arr.dtype)

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

In [ ]:
arr2 > arr

 인덱싱, 슬라이싱


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)

In [ ]:
arr2d[2]

In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0,2]

In [ ]:
arr2d = np.arange(20).reshape(5,4)
arr2d

In [ ]:
arr2d[:2,1:]

Q. array2d에서 슬라이싱을 사용해서 아래와 같이 출력하세요.
```
[[1 2]
[4 5]]

(2가지 방법)
[[4 5 6]
[7 8 9]]

[[1 2 3]
[4 5 6]
[7 8 9]]

[[2 3]
[5 6]]

[1 4]
```

In [ ]:
array2d = np.arange(1,10).reshape(3,3)
print(array2d)

ans1 = array2d[:2,:2]
print(ans1)

In [ ]:
ans2 = array2d[1:,0:]
ans2

In [ ]:
ans3 = array2d[1:]
ans3

In [ ]:
ans4 = array2d
print(ans4)

In [ ]:
ans5 = array2d[:2,1:]
ans5

In [ ]:
ans6 = array2d[0:2,0]
ans6

In [ ]:
# Boolean indexing
array1d = np.arange(1,10)
print(array1d)
array3 = array1d[array1d >5 ]
print(array3)
print(array1d>5)

array1d에서 일반 인덱스를 이용 [6,7,8,9]를 출력하세요.

In [ ]:
# A.
indexes = np.array([5,6,7,8])
array_e2 = array1d[indexes]
# array_e2 = array1d[5:]
print(array_e2)

Q. 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e/2) >5 를 만족하는 값을 불린 인덱스로 출력하세요.

In [ ]:
array_e = np.arange(1,15)
print(array_e)

newarr = array_e[(array_e / 2)>5]

#newarr = (array_e/2)>5
print(newarr)

Q. 1~100까지 정수에서 5의 배수이면서 2의 배수인것만을 출력(for문과 배열 두가지 방식)

In [ ]:
for i in range(1,101):
  if i % 5 == 0 and i % 2 == 0:
    print(i)

In [ ]:
array1 = np.arange(1,101)
array2 = array1[(array1 % 5 == 0) & (array1 % 2 == 0)]
print(array2)

Q. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요

In [ ]:
array1 = np.random.randn(5,5)
array1

In [ ]:
print(array1.mean())
print(array1.std())


Q. 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.

[0,1,2,3,4,5,6,7,8,9]

In [ ]:
array1 = [0,1,2,3,4,5,6,7,8,9]
array1[::-1]

Q.[1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.

In [ ]:
arr =np.array([1,2,0,0,4,0])
print(np.where(arr != 0))

In [ ]:
print(np.nonzero(arr))

팬시 인덱싱

정수 배열을 사용한 인덱싱:
- 정수로 이루어진 배열을 사용하여 다른 배열의 특정 요소를 선택

부울 마스크를 사용한 인덱싱:
- 부울 배열(마스크)을 생성하여, 마스크가 True인 위치의 요소를 선택

정수 배열과 부울 마스크의 결합:
- 이 방법들을 결합하여 더욱 강력한 선택과 수정을 할 수 있다.

In [ ]:
# 정수 배열을 사용한 인덱싱
import numpy as np

arr= np.array([10,20,30,40,50])
index_arr = np.array([0,2,4])
result = arr[index_arr]
print(result)

In [ ]:
# 부울 마스크를 사용한 인덱싱

arr = np.array([10,20,30,40,50])
mask = arr > 25
result = arr[mask]
print(result)

In [ ]:
# 정수 배열과 부울 마스크의 결합
arr= np.array([10,20,30,40,50])
index_arr = np.array([0,2,4])
mask =arr[index_arr] > 20

result = arr[index_arr][mask]
print(result)

In [ ]:
arr = np.empty((8,4))
print(arr, '\n')
for i in range(8):
    arr[i] = i

arr

In [ ]:
arr[[4,3,0,6]]

In [ ]:
arr[[-3,-5,-7]]

In [ ]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')
arr[[1,5,7,2],[0,3,1,2]]#행, 열 인덱스

Q. arr에서 배열[14,21,30]을 출력하세요

In [ ]:
arr[[3,5,7],[2,1,2]]

In [ ]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2,]][:,[0,3,1,2]])

## view
Numpy에서 '뷰(View)'는 원본 배열의 데이터에 대한 새로운 참조. 뷰를 사용하면 원본 데이터를 복사하지 않고도 배열의 일부에 접근하거나 수정할 수 있다.

뷰의 주요 특징과 작동 방식:
- 메모리 효율성: 뷰는 원본 배열의 데이터를 복사하지 않기 때문에, 메모리 사용량이 적다. 뷰는 원본 배열의 메모리에 대한 참조만을 가진다.
- 원본 배열과의 연결: 뷰를 통해 이루어진 변경사항은 원본 배열에도 반영. 마찬가지로, 원본 배열을 변경하면 뷰에도 해당 변경사항이 반영.
- 생성 방법: 뷰는 슬라이싱 연산을 통해 생성될 수 있다. 예를 들어, arr[1:5]와 같은 슬라이싱 연산은 arr 배열의 일부에 대한 뷰를 반환.
- 데이터 타입: 뷰는 원본 배열과 동일한 데이터 타입을 가진다.
- 변경 가능성: 뷰는 원본 데이터를 변경할 수 있는 '가변' 객체.
- 독립성: 뷰는 원본 배열로부터 독립적인 객체. 즉, 뷰에 대한 연산이 원본 배열의 구조에 영향을 주지 않는다(예: 뷰의 모양을 변경해도 원본 배열의 모양은 그대로 유지된다).

#### NumPy에서 'view'를 생성하는 방법
1. 슬라이싱을 사용하여 뷰 생성:
  - 배열의 일부를 슬라이싱하여 뷰를 생성
  - 본 배열의 연속적인 부분에 대한 뷰를 만든다. 예를 들어, arr[1:5]와 같은 표현식은 arr의 일부를 참조하는 뷰를 생성
  - 뷰(view) : 넘파이의 ndarray(이하 배열)을 슬라이싱할 때 파이썬의 리스트(list)와 다르게 원본의 참조가 생성
2. view() 메소드를 사용하여 뷰 생성:
  - view() 메소드는 원본 배열의 데이터를 그대로 유지하면서 새로운 뷰 객체를 생성
  - 이 방법은 슬라이싱과 다르게 배열 전체에 대한 뷰를 생성하며, 데이터 타입(dtype)을 변경할 수도 있다. 예를 들어, arr.view(dtype=np.float32)는 같은 데이터를 float32 타입으로 해석하는 새로운 뷰를 생성
  - view() 메소드를 사용한 뷰는 원본 배열 전체에 대한 새로운 뷰를 생성
  - view() 메소드를 사용하면, 데이터 타입을 변경할 수 있는 추가적인 유연성이 있다. 이 방법은 원본 배열의 전체 데이터에 대한 다른 데이터 타입이나 다른 모양의 해석이 필요할 때 유용

In [ ]:
import numpy as np

#원본 배열 생성
arr = np.array([1,2,3,4])

# arr의 view생성
arr_view = arr.view()

#view 수정
arr_view[0] = 100

# 원본 배열과 view 출력
print("Oraginal array : ", arr)
print('View : ', arr_view)

In [ ]:
original_array = np.array([[1,2,3],[4,5,6]])
print(original_array)

In [ ]:
view_of_array = original_array[:2,:2]
print(view_of_array)

In [ ]:
# 뷰를 통해 이루어진 변경사항은 원본 배열에도 반영
view_of_array[0,0] = 0
print(view_of_array,'\n')
print(original_array)

In [ ]:
# 뷰의 모양을 변경해도 원본 배열의 모양은 그대로 유지된다
reshaped_view = view_of_array.reshape(4)
print(reshaped_view,'\n')
print(original_array)


In [ ]:
#리스트는 뷰를 적용할 수 없음
import numpy as np
li = list(np.arange(1,11))
print(li,'\n')

In [ ]:
li_slice = li[:5].copy()
# li_slice = li[:5]
print(li_slice,'\n')
li_slice[1] = 0
print(li_slice,'\n')
print(li)

In [ ]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
arr

In [ ]:
arr.T

In [ ]:
np.transpose(arr)

#### NumPy 배열의 축(Axes)과 형태(Shape)
- 축(Axes): NumPy 배열에서 각 차원은 '축'이라고 불린다. 예를 들어, 2차원 배열에서 0번 축은 행을, 1번 축은 열을 나타낸다.
- 형태(Shape): 배열의 '형태'는 각 차원의 크기를 튜플로 나타낸 것이다. 예를 들어, 2행 3열의 배열은 (2, 3)의 형태를 가진다.

#### numpy.swapaxes
- 기능: 두 축을 서로 바꾸는(교환하는) 함수
- 사용법: np.swapaxes(arr, axis1, axis2)
  - arr: 배열
  - axis1, axis2: 서로 교환할 축의 번호
- 예시: (2, 3, 4) 형태의 배열에서 축 0과 축 2를 교환하면, 결과 배열의 형태는 (4, 3, 2)가 됩니다.

#### numpy.transpose
- 기능: 축의 순서를 재배열하는 함수입니다.
- 사용법: np.transpose(arr, axes)
  - arr: 배열
  - axes: 축의 새로운 순서를 나타내는 튜플
- 예시: (2, 3, 4) 형태의 배열에 대해 np.transpose(arr, (1, 0, 2))를 사용하면, 결과 배열의 형태는 (3, 2, 4)가 된다.

#### 비교
- swapaxes: 두 축만을 대상으로 서로 위치를 교환.
- transpose: 여러 축의 순서를 완전히 재배열할 수 있으며, swapaxes보다 더 일반적이고 유연.

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a,a.shape)

In [ ]:
# np.swapaxes(a,0,1)를 사용하여 첫 번째 축(0번 축, 즉 행)과 두 번째 축(1번 축, 즉 열)을 교환
y = np.swapaxes(a, 0,1)
#y = np.swapaxes(a, 1,0)
print(y,y.shape)

In [ ]:
y = np.transpose(a)         #np.transpose 전치
print(y,y.shape,'\n')
y=a.T                       #T추가로 T attribute 도 이용할 수 있다
print(y,y.shape)


In [ ]:
#(0,1,2)
a = np.arange(6).reshape(1, 2,3)
print(a,a.shape,'\n')

In [ ]:
# 다차원 배열에서 축의 순서를 재배열하여 배열의 모양을 변경
# (0,1,2) -> (1,0,2) : 첫번째 차원과 두번째 차원을 바꾸라는 의미
print(a,a.shape,'\n')
y = np.transpose(a, (1,0,2))

print(y,y.shape)


Q. a배열에 대해서 첫번째 차원에 두번째 차원을 두번째 차원 자리에 세번째 차원을 세번째 차원 자리에 첫번째 차원을 넣어서 변환하세요

In [ ]:
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

In [ ]:
# (0,1,2) -> (1,2,0) : 첫번째 차원에 두번째 차원을 두번째 차원 자리에 세번째 차원을 세번째 차원 자리에 첫번째 차원
y =  np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
arr = np.arange(1,10).reshape(3,3)
print(arr,'\n')

In [ ]:
print(arr.cumsum())

In [ ]:
# 나머지 구하기를 구할때 사용하는 함수
Value = np.array([15,30,45])
Value1 = np.array([2,7,9])
print(np.mod(Value, Value1))
print(np.remainder(Value, Value1))

In [ ]:
# 각 수으 ㅣ역수를 구해주는 함수 : 0.85의 역수는 1/0.85임
# 0을 역수를 추할 수 없기 때문에 divide by zero에 관련된 Warning 메시지를 표시
Value = np.array([0.85,1.85,1,100])# 기본 float 형태
print(np.reciprocal(Value))

In [ ]:
# 승수의 결과 값을 표시해주는 함수
Value = np.array([2,10,15])
Value1 = np.array([1,2,3])

print(np.power(Value,2),'\n')
print(np.power(Value, Value1))


In [ ]:
np.random.seed(0)
arr = np.random.randn(10)
arr

In [ ]:
(arr>0).sum()#양수인 원소의 개수

In [ ]:
# any 메서드 : 하나 이상의 값이 True인지 검사
bools = np.array([False, False, True,True])
bools.any()


In [ ]:
# all 메서드 : 모든 원소가 True인지 검사
bools.all()

In [ ]:
arr = np.random.randn(6)

np.where(arr >0)

In [ ]:
# numpy.where 함수는 삼향식의 백터화 버전
arr = np.random.randn(4,4)
print(arr)
np.where(arr>0,1,-1)

Q. arr의 모든 양수를 2로 바꾸어서 출력하세요 (음수는 변경없음)

In [ ]:
np.where(arr>0,2,arr)

numpy.meshgrid 함수
- 두 개 이상의 1차원 배열을 입력으로 받아서 각각의 배열을 기반으로 좌표 그리드를 생성하는 함수.
- 이 함수는 종종 함수의 값에 대한 2D 표면 플롯이나 3D 표면 플롯을 생성할 때 유용하게 사용

In [ ]:
# meshgrid 함수
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만둘 수 있는 2ro

In [ ]:
import matplotlib.pyplot as plt
# 1차원 배열 생성
x = np.arange(1, 4)
y = np.arange(1, 4)

# 2D 그리드 생성
xs, ys = np.meshgrid(x, y)

# 좌표 그리기
plt.figure(figsize=(8, 6))
plt.scatter(xs, ys, color='blue')
for i in range(len(x)):
    for j in range(len(y)):
        plt.text(xs[i, j], ys[i, j], f'({xs[i, j]}, {ys[i, j]})', fontsize=12, ha='right')

plt.title('2D Grid Coordinates with np.meshgrid')
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.show()


In [1]:
import numpy as np

my_list = [3,1,2]
s_list = sorted(my_list)
print(s_list)
print(my_list)

[1, 2, 3]
[3, 1, 2]


In [15]:
print(my_list.sort())

None


In [10]:
# np.sort() : 복사본을 반환
arr = np.random.randint(1,100,size=10)
print(arr, '\n')
print(np.sort(arr),'\n')
print(arr)

[41  9 39 95 68  3 14 41 37 57] 

[ 3  9 14 37 39 41 41 57 68 95] 

[41  9 39 95 68  3 14 41 37 57]


In [11]:
sorted = np.sort(arr)
print(sorted)

[ 3  9 14 37 39 41 41 57 68 95]


In [12]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 칼럼방향으로 정렬 수행
array2d = np.array([[8,12],[7,1]])
print(array2d, '\n')
sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0, '\n')
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [13]:
# ndarray.sort() : 원본 반영
arr = np.random.randn(6)
print(arr, '\n')
arr.sort()
print(arr)

[ 1.66050112 -0.81434862 -0.71885362  0.55359398 -0.26764781  1.0251092 ] 

[-0.81434862 -0.71885362 -0.26764781  0.55359398  1.0251092   1.66050112]


In [2]:
# 다차원 배열의 정렬은 sort 메서드에 넘긴 축에 따라 1차원 부분을 정렬
arr = np.random.randn(5,3)
print(arr, '\n')
arr.sort(1)
print(arr)

[[-0.04104448 -1.2782965  -0.05628656]
 [-0.89731951  0.07185912  0.17725886]
 [-0.03921917 -0.65548276 -0.77616646]
 [-0.28395181 -1.84013152  0.78439557]
 [-0.09458916 -2.13439003 -0.96527119]] 

[[-1.2782965  -0.05628656 -0.04104448]
 [-0.89731951  0.07185912  0.17725886]
 [-0.77616646 -0.65548276 -0.03921917]
 [-1.84013152 -0.28395181  0.78439557]
 [-2.13439003 -0.96527119 -0.09458916]]


In [3]:
#default는 0으로 행방향 정렬
arr.sort(0)
arr

array([[-2.13439003, -0.96527119, -0.09458916],
       [-1.84013152, -0.65548276, -0.04104448],
       [-1.2782965 , -0.28395181, -0.03921917],
       [-0.89731951, -0.05628656,  0.17725886],
       [-0.77616646,  0.07185912,  0.78439557]])

In [4]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할때
org_arry = np.array([3,1,9,5])
sort_indices = np.argsort(org_arry)

print(org_arry, '\n')
print(type(sort_indices))
sort_indices

[3 1 9 5] 

<class 'numpy.ndarray'>


array([1, 0, 3, 2])

In [7]:
np.random.seed(0)
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[:5])
large_arr[int(0.05*len(large_arr))] # 5% 분위수

[-3.04614305 -2.83455451 -2.77259276 -2.73967717 -2.65917224]


-1.6326345262344952

NumPy에서 unique, intersect1d, union1d,in1d 함수들은 배열 간의 연산 및 원소 처리

In [8]:
# 배열 x 내의 모든 고유한 원소를 찾아 정렬된 형태로 반환
x = [1,2,2,3,4,4,4]
unique_x = np.unique(x)
print(unique_x)

[1 2 3 4]


In [10]:
# 두 배열 x와 y간의 공통 원소를 찾아 정렬된 형태로 반환
x = [1,2,3,4]
y = [2,3,5,6]
intersect = np.intersect1d(x,y)
intersect

array([2, 3])

In [11]:
# 두 배열 x와 y를 합쳐 모든 고유한 원소를 정렬하여 반호나
x = [1,2,3]
y = [2,3,4,5]
union = np.union1d(x,y)
union

array([1, 2, 3, 4, 5])

In [12]:
# 배열 x의 각 원소가 배열 y에 존재하는지 여부를 불리언 배열로 반환
x = [1,2,3,4]
y = [2,4,6]
result = np.in1d(x,y)
result

array([False,  True, False,  True])

In [13]:
# set 함수는 주어진 반복 가능한 객체(여기서는 names 배열)에서 중복을 제거하고 모든 고유한 원소를 포함하는 집합을 생성
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
# np.unique(names)
set(names)

{'Bob', 'Joe', 'Will'}

In [15]:
#배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장
arr = np.arange(10)
np.save('some_array',arr)

In [16]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz', a= arr,b=arr)


In [19]:
arch = np.load('array_archive.npz')
print(arch['b'])
arch['a']

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. 인덱싱을 사용하여 [1010101010]를 출력하세요

In [25]:
a = np.ones(10, dtype=int)
print(a)
a[[1,3,5,7,9]]=0
print(a)

[1 1 1 1 1 1 1 1 1 1]
[1 0 1 0 1 0 1 0 1 0]


In [20]:
boos= arr%2 ==0

In [22]:
boos*1

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

Q. a배열의 최대값과 최소값의 인덱스를 반환하세요


In [24]:
a=np.arange(1,11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a=np.arange(1,11)
print(a)
print(np.argmax(a))
print(np.argmin(a))

[ 1  2  3  4  5  6  7  8  9 10]
9
0
