## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [4]:
import numpy as np
arr = np.arange(1,13)
print(arr,'\n')
arr = arr.reshape(3,4)
print(arr,'\n')
arr = arr.reshape(2,2,3)
print(arr,'\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [18]:
arr = np.arange(1,13)
print(arr,'\n')
arr1 = arr.reshape(-1,2)
print(arr1,'\n')
arr1 = arr.reshape(-1,3)
print(arr1,'\n')

arr = arr.reshape(-1,2)
arr2 = arr.reshape(-1,1)
print(arr2,'\n')
arr2 = arr.reshape(-1,3)
print(arr2,'\n')

arr = arr.reshape(-1,3)
arr3 = arr.reshape(-1,1)
print(arr3,'\n')
arr3 = arr.reshape(-1,2)
print(arr3,'\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 



Q3. Q1 1차원 배열을 실수형으로 변환

In [19]:
arr = np.arange(1,13)
print(arr,'\n')
arr = arr.astype(float)
print(arr,'\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.] 



Q4. Q1 1차원 배열의 dtype을 확인

In [20]:
print(arr.dtype)

float64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [21]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
arr[arr<0] = 0
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [22]:
arr = np.arange(1,101)
print(arr[arr%3==0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [24]:
arr = np.arange(1,101)
print(arr[(arr%5==0)&(arr%2==0)])

[ 10  20  30  40  50  60  70  80  90 100]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [26]:
arr = np.arange(1,101)
print(arr[(arr%3==0)|(arr%5==0)])

[  3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36  39
  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75  78
  80  81  84  85  87  90  93  95  96  99 100]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [29]:
arr = np.random.randint(101,151,size=(2,5))
print(arr.T)

[[133 150]
 [125 138]
 [107 123]
 [118 131]
 [121 109]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [30]:
arr=np.random.randn(5,5)
arr

array([[ 0.11070458, -0.30253122,  0.66283734, -0.68530051,  1.72922982],
       [ 2.10649836, -0.02255848, -0.08153751, -0.14991249, -0.23831666],
       [ 1.91716106, -1.52034696,  0.19255772, -0.43940269, -0.60862527],
       [ 1.59762284, -0.93406429, -1.51467345, -0.71804275, -0.80212458],
       [-0.08102383,  1.05572793,  0.003927  , -0.74373288,  0.57095409]])

Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [33]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array)
arr = original_array.reshape(-1)
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
View = original_array[0]
View[1] = 123
print(original_array)

[[  1 123   3]
 [  4   5   6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [45]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(original_array)
View = original_array[0]
print(View)
View[1,1] = 55
print(original_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4 55  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
original_array
View = original_array.reshape(-1)
print(View)
View[3] = 444
print(original_array)

[1 2 3 4 5 6]
[[  1   2   3]
 [444   5   6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [66]:
arr = np.ones((10,10))
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [ ]:
arr = np.arange(1,101)
arr = arr.reshape(10,10)
arr

In [106]:

for i in range(1,11,2):
    pop = arr1[i,:][::-1]
    arr[i,:] = pop

arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [109]:
arr = np.ones((10,10))
arr[2:8,2:8] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.