Task1_0723. 'Breast Cancer Wisconsin (Diagnostic) Data Set'을 사용하여 이진 분류 문제를 해결하고, 평가 지표(정확도, 정밀도, 재현율, F1 스코어, ROC AUC)를 계산하세요.

In [8]:
# 데이터 로드
import pandas as pd
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.info()
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.3, random_state=43)

model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(accuracy_score(y_test, pred))
print(precision_score(y_test, pred))
print(recall_score(y_test, pred))
print(f1_score(y_test, pred))
print(roc_auc_score(y_test, pred))

0.9766081871345029
0.9824561403508771
0.9824561403508771
0.9824561403508771
0.9736842105263157


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Task2_0723.
가상의 데이터셋을 생성하고, 이를 사용하여 다중 클래스 분류 모델을 훈련시킨 후 평가 지표를 계산하세요. 평가 지표는 정확도, 정밀도, 재현율, F1 스코어, ROC AUC입니다.

- n_samples=1500: 데이터셋에 포함될 샘플의 수를 1500개로 지정합니다.
- n_features=20: 각 샘플이 가질 특성(feature)의 수를 20개로 지정합니다.
- n_classes=5: 타겟 라벨의 클래스 수를 5개로 지정합니다.
- n_informative=15: 20개의 특성 중 15개는 타겟 라벨과 관련된 유용한 정보를 포함하도록 지정합니다. 나머지 5개의 특성은 유용하지 않거나 무작위로 생성된 특성입니다.
- random_state=42: 재현성을 위해 난수 생성 seed를 설정합니다.

In [34]:
# 데이터 생성 (5개의 클래스)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.preprocessing import label_binarize

X, y = make_classification(n_samples=1500, n_features=20, n_classes=5, n_informative=15, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=43)


y_test_binarized = label_binarize(y_test, classes=[0, 1, 2, 3, 4])
model = LogisticRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)
print(accuracy_score(y_test, pred))
print(precision_score(y_test, pred, average='macro'))
print(recall_score(y_test, pred, average='macro'))
print(f1_score(y_test, pred, average='macro'))
print(roc_auc_score(y_test_binarized, y_pred_proba, multi_class='ovr'))

0.5911111111111111
0.594241262608782
0.589090035950308
0.5906981184106177
0.8498897825178652


In [24]:
y_test_binarized

array([[0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [27]:
y_test

array([4, 0, 0, 0, 1, 3, 2, 0, 3, 0, 0, 0, 3, 1, 2, 4, 3, 1, 2, 4, 1, 0,
       1, 2, 1, 2, 0, 3, 2, 3, 2, 3, 1, 0, 4, 4, 3, 1, 1, 3, 4, 1, 3, 3,
       3, 4, 2, 1, 4, 3, 2, 1, 4, 1, 1, 4, 0, 0, 1, 4, 4, 2, 4, 2, 2, 4,
       4, 1, 3, 3, 1, 3, 0, 3, 1, 3, 3, 3, 2, 2, 1, 0, 1, 4, 3, 1, 4, 4,
       1, 4, 4, 4, 2, 0, 4, 0, 3, 1, 2, 4, 1, 1, 1, 1, 4, 1, 1, 4, 4, 0,
       3, 0, 4, 1, 0, 1, 0, 0, 4, 1, 1, 3, 0, 4, 1, 0, 2, 4, 2, 3, 0, 3,
       0, 2, 4, 0, 2, 2, 1, 3, 4, 4, 1, 0, 3, 3, 3, 2, 0, 2, 0, 2, 3, 4,
       2, 1, 0, 0, 3, 2, 3, 4, 3, 0, 1, 4, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2,
       1, 3, 3, 1, 0, 1, 2, 4, 4, 2, 4, 3, 4, 4, 3, 0, 4, 1, 0, 4, 2, 2,
       2, 1, 0, 1, 0, 4, 1, 3, 1, 0, 1, 2, 2, 2, 0, 1, 4, 1, 0, 4, 1, 1,
       0, 3, 2, 4, 1, 4, 0, 4, 3, 1, 2, 2, 3, 2, 0, 4, 0, 0, 0, 0, 0, 1,
       3, 0, 1, 2, 0, 4, 3, 1, 4, 0, 1, 0, 1, 3, 3, 2, 0, 4, 2, 0, 2, 0,
       3, 2, 2, 0, 3, 3, 0, 3, 3, 1, 1, 2, 1, 2, 2, 1, 1, 4, 1, 4, 2, 1,
       3, 0, 2, 2, 4, 4, 3, 2, 3, 0, 0, 0, 0, 1, 0,

In [25]:
X


array([[ 2.52617945,  2.29280822,  0.618991  , ...,  1.36499237,
         0.05218953, -1.30012089],
       [ 0.1914641 ,  2.78145056,  1.88992682, ..., -0.9904858 ,
        -0.38473831, -1.63043413],
       [ 0.89761552, -1.73735125,  1.79534211, ...,  0.37633328,
         1.71220325, -1.05090873],
       ...,
       [-0.35483315,  1.1363709 ,  0.49983059, ...,  1.01733854,
        -2.20858075,  1.01404779],
       [-0.47463847,  0.4423352 , -1.56861684, ..., -0.23308884,
        -2.88881257, -1.5752226 ],
       [ 0.99907235, -2.4921969 ,  1.65144204, ...,  1.03013986,
        -3.60381327,  0.9168089 ]])

In [26]:
y

array([2, 3, 2, ..., 3, 3, 2])

#개조

In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. 데이터 로드
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
           'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
           'hours-per-week', 'native-country', 'income']
data = pd.read_csv(url, header=None, names=columns, na_values='?', skipinitialspace=True)

# 2. 결측치 처리
# 수치형 변수의 결측치를 중앙값으로 대체
numeric_features = data.select_dtypes(include=[np.number]).columns.tolist()
imputer_numeric = SimpleImputer(strategy='median')
data[numeric_features] = imputer_numeric.fit_transform(data[numeric_features])

# 범주형 변수의 결측치를 최빈값으로 대체
categorical_features = data.select_dtypes(include=[object]).columns.tolist()
categorical_features.remove('income')
imputer_categorical = SimpleImputer(strategy='most_frequent')
data[categorical_features] = imputer_categorical.fit_transform(data[categorical_features])

# 3. 이상치 제거 (여기서는 'capital-gain'과 'capital-loss'에서 극단적인 값들을 이상치로 가정)
def replace_outliers_with_median(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    median = df[column].median()
    df[column] = np.where((df[column] < lower_bound) | (df[column] > upper_bound), median, df[column])
    return df

for col in numeric_features:
    data = replace_outliers_with_median(data, col)

# 4. 파생변수 작성
data['capital_diff'] = data['capital-gain'] - data['capital-loss']

# 5. 범주형 변수 인코딩
categorical_features = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
encoder = OneHotEncoder(drop='first', sparse=False)
encoded_categorical_data = encoder.fit_transform(data[categorical_features])
encoded_categorical_df = pd.DataFrame(encoded_categorical_data, columns=encoder.get_feature_names_out(categorical_features))

# 원래 데이터프레임에서 범주형 열을 제거하고 인코딩된 데이터프레임을 병합
data = data.drop(columns=categorical_features)
data = pd.concat([data, encoded_categorical_df], axis=1)

# 6. 변수 선택 및 데이터 분리
# 'income' 변수를 0과 1로 변환
data['income'] = data['income'].apply(lambda x: 1 if x.strip() == '>50K' else 0)
X = data.drop('income', axis=1)
y = data['income']

# 7. 데이터 표준화
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 8. 학습용과 테스트용 데이터셋으로 나누기
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# 9. Logistic Regression 모델 생성 및 학습
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

# 10. 예측 및 평가
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Accuracy: 0.83
Confusion Matrix:
[[4563  382]
 [ 706  862]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.92      0.89      4945
           1       0.69      0.55      0.61      1568

    accuracy                           0.83      6513
   macro avg       0.78      0.74      0.75      6513
weighted avg       0.82      0.83      0.83      6513



In [37]:
data

age    fnlwgt  education-num  capital-gain  capital-loss  \
0      39.0   77516.0           13.0           0.0           0.0   
1      50.0   83311.0           13.0           0.0           0.0   
2      38.0  215646.0            9.0           0.0           0.0   
3      53.0  234721.0            7.0           0.0           0.0   
4      28.0  338409.0           13.0           0.0           0.0   
...     ...       ...            ...           ...           ...   
32556  27.0  257302.0           12.0           0.0           0.0   
32557  40.0  154374.0            9.0           0.0           0.0   
32558  58.0  151910.0            9.0           0.0           0.0   
32559  22.0  201490.0            9.0           0.0           0.0   
32560  52.0  287927.0            9.0           0.0           0.0   

       hours-per-week  income  capital_diff  workclass_Local-gov  \
0                40.0       0           0.0                  0.0   
1                40.0       0           0.0                  0.0   
2                40.0       0           0.0                  0.0   
3                40.0       0           0.0                  0.0   
4                40.0       0           0.0                  0.0   
...               ...     ...           ...                  ...   
32556            38.0       0           0.0                  0.0   
32557            40.0       1           0.0                  0.0   
32558            40.0       0           0.0                  0.0   
32559            40.0       0           0.0                  0.0   
32560            40.0       1           0.0                  0.0   

       workclass_Never-worked  ...  native-country_Portugal  \
0                         0.0  ...                      0.0   
1                         0.0  ...                      0.0   
2                         0.0  ...                      0.0   
3                         0.0  ...                      0.0   
4                         0.0  ...                      0.0   
...                       ...  ...                      ...   
32556                     0.0  ...                      0.0   
32557                     0.0  ...                      0.0   
32558                     0.0  ...                      0.0   
32559                     0.0  ...                      0.0   
32560                     0.0  ...                      0.0   

       native-country_Puerto-Rico  native-country_Scotland  \
0                             0.0                      0.0   
1                             0.0                      0.0   
2                             0.0                      0.0   
3                             0.0                      0.0   
4                             0.0                      0.0   
...                           ...                      ...   
32556                         0.0                      0.0   
32557                         0.0                      0.0   
32558                         0.0                      0.0   
32559                         0.0                      0.0   
32560                         0.0                      0.0   

       native-country_South  native-country_Taiwan  native-country_Thailand  \
0                       0.0                    0.0                      0.0   
1                       0.0                    0.0                      0.0   
2                       0.0                    0.0                      0.0   
3                       0.0                    0.0                      0.0   
4                       0.0                    0.0                      0.0   
...                     ...                    ...                      ...   
32556                   0.0                    0.0                      0.0   
32557                   0.0                    0.0                      0.0   
32558                   0.0                    0.0                      0.0   
32559                   0.0                    0.0                      0.0   
325